require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - 'x'
    - 'x1'
    - 'x2'
    - 'y'
    - 'y1'
    - 'y2'

RSpec/MultipleExpectations:
  AggregateFailuresByDefault: true

RSpec/NestedGroups:
  Max: 4

RSpec/InstanceVariable:
  Exclude:
    - 'spec/support/bitmap_context.rb'
    - 'spec/support/area_context.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/bitmap_spec.rb'
    - 'spec/area_spec.rb'
    - 'spec/utility/bresenham_spec.rb'
    - 'spec/validators/two_dimensional_coordinates_validator_spec.rb'

Metrics/BlockLength:
  ExcludedMethods:
    - 'it'
    - 'describe'
    - 'context'

Metrics/LineLength:
  Max: 122
